version: '3.3'
services:
  server:
    build: server
    depends_on:
    - mongodb
  client:
    build: client
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d/savo.conf:/srv/conf.d/savo.conf:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/opt:ro
    depends_on:
    - server
    - client
  mongodb:
    image: mongo:latest
    volumes:
    - ./data:/data/db:rw
